proto/query/query.go

Add original size of the Query, before any truncation.
Related PRs:
* https://github.com/percona/qan-api/pull/52
* https://github.com/percona/go-mysql/pull/28
* https://github.com/percona/qan-app/pull/79
* https://github.com/percona/pmm/pull/135

PMM-1899: Add size to determine if query got truncated.

---

doc/Dockerfile

Needs to be a specific version of Sphinx 1.6.7, Wget is missing from most of the Docker images, that needs to be installed

PMM-3763 Adding DockerFile for Sphinx doc build

---

.golangci.yml
api/Gopkg.lock
api/Gopkg.toml
api/Makefile
api/agentpb/agent.go
api/agentpb/metadata.go
api/inventorypb/agents.go
api/inventorypb/nodes.go
api/inventorypb/services.go

One of the major pain points mentioned by @DexterHD recently was that we don't have a linter for problems like [that](https://github.com/percona/pmm-managed/commit/aa725f7698564d0d77847b2b5dba435990080a08). Those problems are also not obvious during code reviews. Now they are.
Previously, I tried to use https://github.com/haya14busa/gosum, but it did not really work. Last week I found https://github.com/BurntSushi/go-sumtype. It covers some of our problems and does not have false positives, so that should be an improvement. Please read its README to understand how it works.
While working on it, I also simplified some code in pmm-agent and pmm-managed to use new interfaces. For example, instead of
```go
SendResponse(&agentpb.AgentMessage{
Id: serverMessage.Id,
Payload: …
```

Add exhaustiveness checks on our "sum types".

---

.travis.yml

- Made it skip non-trunk PMM-XXXX branch builds, but still build pull requests.

PMM-4010 travis go 1.13.x

---

doc/source/security.rst

Left out how to confirm secure cookies as it involves opening dev tools in a browser and searching for a named cookie.

Added basic steps (without confirmation)

---

get-pmm.sh

The default terminal window for a fresh ubuntu install makes the URL's unreadable with the blue on black...changing to green but feel free to choose a different color.

Improvements to get-pmm.sh script for readability and Mac users

---

agent/utils/version/mysql.go
agent/utils/version/mysql_test.go

Since the repos were joined, I am re-applying https://github.com/percona/pmm-agent/pull/386/files here.
[PMM-9998](https://jira.percona.com/browse/PMM-9998) Again: Error 1054: Unknown column 'performance_schema.events_statements_summary_by_digest.QUERY_SAMPLE_TEXT' in 'field list'

PMM-9998 Re-applying PR #386 from pmm-agent repo

---

api-tests/server/updates_test.go
managed/services/server/server.go

PMM-10082
Build: SUBMODULES-2601
This PR fixes failing API Tests on SSH key validation.
The `ssh-keygen` utility has been removed from the Docker image and is no longer available.

PMM-10082 Remove ssh-keygen dependency

---

agent/docker-compose.yml

PMM-6384 Fixed docker-compose for M1 CPUs

---

.github/workflows/common.yml

Common tests are required to pass, and it is hard to workaround this report in Actions.

return common test for docs

---

docs/api/dbaas.md

this is a small fix for kubeconfig generation.
don't know why it has `--` maybe if minikube aliased as `alias kubectl='minikube kubectl'` when it should be `alias kubectl='minikube kubectl --'`.
Anyway it should be fixed, doesn't work in current form.

fix issue in get config

---

.sha256-oneline

We don't use this file for quick install script anymore.
PMM-7

PMM-7 remove old hash for quick-install script

---

CONTRIBUTING.md
README.md

Improving PMM Readme
1. Added comments to the docker commands, I think it will be better to let the user know what these commands are doing in general and how to open the dashboard.
2. CLA link fixed, it was giving "the page does not exist" so, I added this **https://cla-assistant.percona.com/percona/grafana-dashboards** (correct me if this link is wrong) instead of **https://cla-assistant.percona.com/<linktoCLA>**
Any feedback is appreciated!

Improve pmm readme documentation

---

api-tests/server/logs_test.go
managed/services/supervisord/logs_test.go

PMM-5680
Build: SUBMODULES-2683
Update test **TestDownloadLogs** https://pmm.cd.percona.com/job/pmm2-api-tests/10821/consoleFull (SUBMODULES-2679)
TestDownloadLogs: https://github.com/percona/pmm/blob/fad149453944960b7a1373b3c039485dbc4d02ef/api-tests/server/logs_test.go#L95

PMM-5680 fix API tests

---

.github/workflows/common.yml

Disable optional linters run until this issue will be resolved: https://github.com/reviewdog/action-golangci-lint/issues/432

Run optional linters only for pull requests

---

managed/models/database_test.go

Closes #1296
The `stats_collection` field migration test in `database_test` was wrongly implemented. This PR fixes it by:
- using migration number `58` instead of `68`
- using SQL query instead of `reform` to insert dummy agent in DB

Fix stats_collection field migration test

---

managed/utils/envvars/parser.go
managed/utils/envvars/parser_test.go

When the host system has a proxy configured, warnings are emitted in the pmm-managed log due to their absence in the validation of environment variables.
Similarly, when PMM Server is running in a container via podman then the `container` environment variable triggers a warning too.
* Updated parsing to allow `NO_PROXY`, `HTTP_PROXY`, `HTTPS_PROXY` and the respective lowercase versions, along with the special podman variable, `container`
* Added test case for optional environment variables, where optional means that they may exist with or without direct specification by the user
[PMM-5939](https://jira.percona.com/browse/PMM-5939)
Build: [SUBMODULES-2798](https://github.com/Percona-Lab/pmm-submodules/pull/2798)

PMM-5939 ParseEnvVars notifies about proxy variables

---

managed/services/agents/registry.go

PMM-0
Catch this data race when work on PMM-11154
```go
package pmm
import (
"sync"
"testing"
)
func BenchmarkMapRaceLenUnsafe(b *testing.B) {
var (
data = make(map[int]bool, b.N)
wg   sync.WaitGroup
mu   sync.Mutex
)
wg.Add(1)
go func() {
defer wg.Done()
for i := 0; i < b.N; i++ {
mu.Lock()
data[i] = true
mu.Unlock()
}
}()
wg.Add(1)
go func() {
defer wg.Done()
for i := 0; i < b.N; i++ {
// PANIC
_ = len(data)
}
}()
wg.Wait()
}
func BenchmarkMapLenSafe(b *testing.B) {
var (
data = make(map[int]bool, b.N)
wg   sync.WaitGroup
mu   sync.Mutex
)
wg.Add(1)
go func() {
defer wg.Done()
for i := 0; i < b.N; i++ {
mu.Lock()
data[i] = true
mu.Unlock()
}
}()
wg.Add(1)
go func() {
defer wg.Done()
for i := 0; i < b.N; i++ {
mu.Lock()
_ = len(data)
mu.Unlock()
}
}()
wg.Wait()
}
```

PMM-0 fix data race

---

managed/services/dbaas/kubernetes/types.go

DecimalSI calculation does not work for PXC clusters with fraction values. PXC gives the calculated "2.4G" is not valid and if I manually override that to 3G it is working fine.
PMM-0

PMM-11387 Fixed calculation for gcache setting depending on memory size available 

---

update/ansible/playbook/tasks/update.yml

PMM-11372
Fixes issue with a broken update due to missing `vmproxy` binary.

PMM-11372: add vmproxy to update task

---

.golangci.yml
admin/commands/inventory/inventory.go
managed/models/models.go
managed/models/node_helpers.go
managed/services/checks/funcs.go
managed/services/management/dbaas/psmdb_cluster_service.go
managed/services/management/dbaas/pxc_cluster_service.go

PMM-7
Note: this PR re-enables the `ninil` linter rule and fixes the warnings thereof. Even though I mostly had to resort to disabling all warnings with `nolint`, IMO it is still a good rule to follow for the sake of more semantic code. 
Fixing this rule in the code would have required us to re-test the code in a number of components, which wasn't the gole of this PR.

PMM-7 re-enable the `nilnil` linter rule

---

.golangci.yml
api-tests/server/auth_test.go
vmproxy/proxy/proxy_test.go

PMM-7
Note: this PR re-enables the `bodyclose` linter rule and fixes the warnings.

PMM-7 fix bodyclose linter warnings

---

managed/services/management/rds.go

PMM-7
Why:
It was showing up in every PR as a linter warning, too annoying...

PMM-7 fix the use of deprecated `RdsServiceID` constant

---

.golangci.yml
api-tests/management/alerting/alerting_test.go
managed/services/management/dbaas/kubernetes_server.go
managed/services/management/dbaas/psmdb_cluster_service.go
managed/services/management/dbaas/pxc_cluster_service.go

PMM-7
This PR re-enables the `whitespace` rule and fixes the warnings thereof.

PMM-7 re-enable `whitespace` linter rule

---

.golangci.yml
api/main_test.go
managed/services/dbaas/kubernetes/types.go
managed/services/management/backup/locations_service_test.go

PMM-7
Refer to: https://github.com/percona/pmm/issues/1541
This PR:
1/ disables the linter rule `deadcode`, since `unused` does the same
2/ fixes the remaining `whitespace` warnings

PMM-7 disable `deadcode` linter rule

---

.golangci.yml
agent/agents/supervisor/supervisor.go
qan-api2/services/analytics/filters_test.go
qan-api2/services/analytics/metrics_names_test.go
qan-api2/services/analytics/object_details_test.go
qan-api2/services/analytics/profile_test.go

PMM-7
This PR re-enables the `containedctx` linter rule and fixes linter warnings thereof.

PMM-7 re-enable `containedctx` linter rule

---

.golangci.yml
admin/commands/summary.go

PMM-7
This PR re-enables the `nosprintfhostport` linter rule and fixes the warnings thereof.

PMM-7 re-enable the `nosprintfhostport` linter rule

---

.golangci.yml
admin/commands/inventory/list_agents.go
admin/commands/inventory/list_nodes.go
admin/commands/inventory/list_services.go
admin/commands/list.go
agent/agents/postgres/parser/parser.go
api-tests/management/helpers.go
managed/services/alertmanager/alertmanager.go
managed/services/management/dbaas/db_cluster_service.go
managed/services/management/ia/alerts_service.go
managed/services/telemetry/config.go
qan-api2/services/analytics/profile.go

PMM-7
This PR re-enables the `prealloc` linter rule and fixes the warnings thereof. We suppress the rule in tests and in cases where it's impractical to calculate the array length.

PMM-7 re-enable the `prealloc` linter rule

---

.golangci.yml
agent/agents/supervisor/supervisor.go

PMM-7
This PR re-enables the `predeclared` linter rule and fixes the warnings thereof.

PMM-7 re-enable the `predeclared` linter rule

---

Makefile

It's been some time since major Docker distributions adopted the docker "compose" plugin, which is mostly installed by default. Therefore, we'd benefit from using it instead of the "docker-compose" utility, which needs to be provisioned additionally.
PMM-7

PMM-7 use `compose` plugin of docker

---

.golangci.yml
Makefile.include
agent/utils/mongo_fix/mongo_fix.go
managed/Makefile
managed/cmd/pmm-managed/main.go

PMM-7
Ref: issue #1541 
Changes:
- disable the `golint` rule as [unmaintained](https://github.com/golang/lint)
- fix a couple of lint warnings that are present in `main` branch
- add a possibility to pass arbitrary files to managed's `make test ...` command

PMM-7 disable `golint` rule

---

.golangci.yml
admin/commands/base/setup.go
agent/agents/mysql/perfschema/perfschema.go
agent/agents/postgres/pgstatmonitor/stat_monitor_cache.go
agent/cmd/pmm-agent-entrypoint/main.go
agent/runner/actions/postgresql_show_create_table_action.go
managed/services/dbaas/kubernetes/types.go
managed/services/management/backup/locations_service_test.go
managed/services/management/dbaas/dbaas_initializer.go
managed/services/management/dbaas/version_service_client_test.go

Ref: issue https://github.com/percona/pmm/issues/1541
Changes:
1/ enable the rule, set the min-complexity to 7
2/ fix linter warnings
Note: setting min-complexity to 7 seems to be a balance between too strict (default is 5) and too lax. Please comment if we want a different setting.

PMM-7 enable `nestif` linter rule

---

.golangci.yml
agent/agents/mysql/slowlog/slowlog.go
agent/agents/mysql/slowlog/slowlog_test.go
agent/agents/postgres/pgstatmonitor/pgstatmonitor.go
managed/services/management/dbaas/version_service_client.go

Ref: issue #1541 
Changes:
* enabled the rule
* fixed a couple of other linter errors
Note: `nakedret` was mostly fixed along with `nonamedreturns `, so there was only one left.

PMM-7 enable the `nakedret` lint rule

---

.github/workflows/admin.yml

Temporary disabled upgrade tests by pmm-bin as it hangs forever.

PMM-11991 disabled upgrade tests temporary

---

.github/CODEOWNERS
update/.devcontainer/install-dev-tools.sh

PMM-7
This PR fixes the failing update tests, where we use the `dev-latest` image, which is already RHEL9 based.

PMM-7 fix update test for RHEL9

---

.golangci.yml
update/.devcontainer/install-dev-tools.sh

PMM-7
Ref: #1541 
Ref: https://github.com/mibk/dupl
This PR disables the rule since we can't really avoid code duplication between different services of a component as well as between different components of this monorepo.

PMM-7 disable `dupl` linter rule

---

update/ansible/playbook/tasks/roles/dashboards_upgrade/tasks/main.yml

PMM-12235
This backports the PR https://github.com/percona/pmm/pull/2290 to branch 2.38.0.

PMM-12235 remove old clickhouse plugin

---

build/ansible/roles/ami-ovf/tasks/main.yml

PMM-12248
AMI (EL9) with the fix can be found at: 
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ami/detail/pmm2-ami/5080/pipeline/41/

PMM-12248 Fix supervisorctl path on EL-9.

---

.github/workflows/admin.yml

PMM-7
PMM CLI is not a GA feature yet. Since its tests are not stable, we want to temporarily disable them.

PMM-7 temporarily disable PMM CLI tests

---

build/scripts/create-tags

This fixes a bug in the script, that is preventing it from detecting the existing repository tag.
PMM-7

PMM-7 Fix improper repository tag detection

---

build/ansible/pmm2/main.yml
build/ansible/roles/cloud-node/tasks/main.yml
build/ansible/roles/pmm2-images/tasks/main.yml
build/docker/server/Dockerfile.el9
build/packer/pmm2.el9.json
update/ansible/playbook/tasks/update.yml

Reverts percona/pmm#2446
Following the merge of (https://github.com/percona/pmm/pull/2446), we’ve encountered some CI failures, such as in this example: https://github.com/percona/pmm/actions/runs/6084707881/job/16507204096
_**TASK [Update system packages] **************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failures": [], "msg": "Depsolve Error occurred: \n Problem: package ansible-5.4.0-2.el9.noarch requires (python3.9dist(ansible-core) >= 2.12.2 with python3.9dist(ansible-core) < 2.13), but none of the providers can be installed\n  - cannot install both ansible-core-2.14.2-5.el9_2.x86_64 and ansible-core-2.12.2-2.el9_0.x86_64\n  - cannot install both ansible-core-2.14.2-5.el9_2.x86_64 and ansible-core-2.12.2-1.el9.x86_64\n  - cannot …

Revert "PMM-9769 update all components"

---

build/packages/rpm/server/SPECS/pmm-dump.spec
build/packages/rpm/server/SPECS/victoriametrics.spec
build/scripts/vars

PMM-12488
Link to the Feature Build: SUBMODULES-3390
- https://github.com/percona/pmm-qa/pull/639
- https://github.com/Percona-Lab/pmm-submodules/pull/3390

PMM-12488 update VictoriaMetrics to v1.93.4

---

update/ansible/playbook/tasks/roles/initialization/tasks/main.yml
update/ansible/playbook/tasks/roles/sqlite-to-postgres/tasks/main.yml
update/ansible/playbook/tasks/update.yml

PMM-12494
Link to the Feature Build: SUBMODULES-3389

PMM-12494 fix sqlite to postgres for docker

---

update/ansible/playbook/tasks/roles/initialization/tasks/main.yml
update/ansible/playbook/tasks/update.yml

PMM-7 fix UI upgrade

---

.golangci.yml
agent/runner/jobs/pbm_helpers.go
managed/services/agents/grpc/agent_server.go
managed/services/agents/log_level.go
managed/services/backup/backup_service.go
managed/services/backup/compatibility_service.go
managed/services/backup/pitr_timerange_service.go
managed/services/dbaas/kubernetes/client/client.go
managed/services/dbaas/kubernetes/client/kubeclient_interface.go
managed/services/dbaas/kubernetes/kubernetes.go
managed/services/management/backup/backups_service.go
managed/services/management/grpc/actions_server.go
managed/services/management/grpc/mongodb_server.go
managed/services/management/grpc/mysql_server.go
managed/services/management/grpc/node_server.go
managed/services/management/grpc/postgresql_server.go
managed/services/management/grpc/proxysql_server.go
managed/services/management/ia/rules_service.go
managed/services/telemetry/telemetry.go
managed/services/telemetry/telemetry_test.go

PMM-7
This PR:
1/ fixes the linter configuration for the `depguard` [rule](https://golangci-lint.run/usage/linters/#depguard) 
2/ fixes some - not all (!) - linter errors
Team, feel free to contribute to more linter error fixes 👋

PMM-7 Fix linter config and some errors

---

update/ansible/playbook/tasks/roles/clickhouse/files/config.xml

Ref: PMM-12223
Ref: [failing API test run](https://pmm.cd.percona.com/job/pmm2-api-tests/14311/consoleFull)
**Why**:
PMM API tests currently fail. Namely, `TestDownloadLogs` fails with the following diff:
```
12:38:56          	            	Diff:
12:38:56          	            	--- Expected
12:38:56          	            	+++ Actual
12:38:56          	            	@@ -1,2 +1,2 @@
12:38:56          	            	-([]string) (len=38) {
12:38:56          	            	+([]string) (len=39) {
12:38:56          	            	  (string) (len=21) "alertmanager.base.yml",
12:38:56          	            	@@ -5,2 +5,3 @@
12:38:56          	            	  (string) (len=16) "alertmanager.yml",
12:38:56          	            	+ (string) (len=25) "clickhouse-server.err.log",
12:38:56 …
```

PMM-7 fix API tests

---

update/ansible/playbook/tasks/roles/initialization/tasks/main.yml
update/ansible/playbook/tasks/update.yml

PMM-12576
Link to the Feature Build: SUBMODULES-3418

PMM-12576 change admin ID to 1.

---

update/ansible/playbook/tasks/roles/nginx/files/conf.d/pmm.conf

We have keepalives enabled in upstream blocks, but some of the locations are missing the proxy changes required to use it. 
[10 top nginx configuration mistakes](https://www.nginx.com/blog/avoiding-top-10-nginx-configuration-mistakes/#no-keepalives)
This is contributed as part of Percona support case **CS0040376**.

Missing settings to use keepalive in some locations

---

managed/models/agentversion.go
managed/models/agentversion_test.go

PMM-12702
Link to the Feature Build: SUBMODULES-3449

PMM-12702 Fix SSLSni checker.

---

managed/services/agents/agents.go
managed/services/agents/agents_test.go
managed/services/agents/mongodb_test.go
managed/services/agents/mysql_test.go
managed/services/agents/node_test.go
managed/services/agents/postgresql_test.go
managed/services/agents/proxysql_test.go
managed/services/agents/state.go

PMM-12422
Due to issues with getting metrics when using the node IP, this exposes exporters running in pull mode on the public IP address.

PMM-12422 use public IP for exporters in pull mode

---

.github/workflows/managed.yml
managed/services/grafana/client_test.go

PMM-7
CI currently fails because the health checks for pmm-server container is failing. This applies a workaround copied from https://github.com/percona/pmm/pull/2777 as a temporary workaround.

PMM-7: extract test env workaround

---

build/docker/rpmbuild/Dockerfile.el9

PMM-7
This patch fixes the problem where NodeJS install script requires either `dnf` or `yum` as a package manager. If those can't be found, the script fails. It seems like the behavior must have changed in the recent versions of the script.
Tested: https://pmm.cd.percona.com/job/rpm-build-3/4/console

PMM-7 install yum prior to installing NodeJS

---

.github/workflows/main.yml

They not only bumped up the version. This action now calls a [third-party action](https://github.com/rtCamp/action-slack-notify/compare/v2.2.1...v2.3.0#diff-1243c5424efaaa19bd8e813c5e6f6da46316e63761421b3e5f5c8ced9a36e6b6R10), which is not listed with us. I was afraid it may leak secrets, so we'd better pin the version we know.
PMM-7

PMM-7 fix action-slack-notify

---

api-tests/server/advisors_test.go

PMM-7
Following this protobuf change, unknown enums no longer returns an error for us, this caused the previous grpc error check to fail (since the test was expecting an error).
This change drops the error check, and now the test just confirms that the check intervals remain unchanged.
Link to the Feature Build: 
SUBMODULES-3600

PMM-7: update test to check that intervals remain unchanged

---

build/ansible/roles/initialization/tasks/main.yml

This fixes a bug where, due to a wrong ansible formula, PMM would upgrade the dashboards no matter what :)
PMM-12641
Link to the Feature Build: SUBMODULES-3599
<details><summary>Faulty logs</summary>
<p>
[ec2-user@ip-10-178-1-214 ~]$ docker exec pmm-server cat /srv/logs/pmm-update-perform-init.log
ProjectName: pmm-update
Version: 3.0.0
PMMVersion: 3.0.0
Timestamp: 2024-03-21 00:22:05 (UTC)
FullCommit: f9fd3a773f757c4cdfedc86681093eabdf6095d3
Starting "ansible-playbook --flush-cache /opt/ansible/pmm-docker/init.yml" ...
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'
PLAY [localhost] ***************************************************************
TASK [Gathering Facts] …

PMM-12641 Fix the dashboard upgrade

---

managed/services/grafana/client.go

Service accounts fix for grafana when max length is exceeded.

PMM-7 Service accounts length fix.

---

.github/workflows/admin.yml
.github/workflows/agent.yml
.github/workflows/managed.yml
.github/workflows/update.yml
.github/workflows/vmproxy.yml

**Background**
We lost codecov.io uploads for some reason. Maybe because of `CODECOV_TOKEN`, which wasn't being passed.
This PR is to rectify that and upgrade codecov's action to the latest.

PMM-7 Upgrade codecov-action

---

.github/workflows/clean.yml
Dockerfile
build/docker/rpmbuild/Dockerfile
build/docker/rpmbuild/Dockerfile.el9
devcontainer.Dockerfile
tools/go.mod
tools/go.sum
update/.devcontainer/install-dev-tools.sh
update/docker-compose.yml

PMM-7
This PR should aid in making [dependabot](https://github.com/percona/pmm/pull/2985) PRs pass.
TODO: publish the `rpmbuild` containers before merging

PMM-7 upgrade Go to v1.22

---

agent/agents/mysql/perfschema/perfschema.go
agent/agents/mysql/slowlog/slowlog.go
agent/connectionchecker/connection_checker.go
agent/runner/actions/common.go
agent/runner/actions/mysql_explain_action.go
agent/runner/actions/mysql_query_select_action.go
agent/runner/actions/mysql_query_show_action.go
agent/runner/actions/mysql_show_create_table_action.go
agent/runner/actions/mysql_show_index_action.go
agent/runner/actions/mysql_show_table_status_action.go
agent/serviceinfobroker/service_info_broker.go
agent/tlshelpers/mysql.go
managed/models/agent_model.go

Merged in v2. PR created to include it also into v3.

PMM-12880 Proper skip for MySQL TLS certs. (#2909).

---

managed/models/agent_helpers.go
managed/models/agent_model.go
managed/models/agent_model_test.go
managed/models/dsn_helpers.go
managed/services/agents/connection_checker.go
managed/services/agents/mongodb.go
managed/services/agents/mysql.go
managed/services/agents/postgresql.go
managed/services/agents/proxysql.go
managed/services/agents/service_info_broker.go
managed/services/agents/state.go

* PMM-13145 Fix for older clients.
* PMM-13145 Small changes.
* PMM-13145 Lint.
* PMM-13145 Lint.
* PMM-13145 Logic fix.
* PMM-13145 Refactor.
* PMM-13145 Fix after refactor.
* Update managed/models/agent_model.go
* Update managed/models/agent_model.go
---------
PMM-0

PMM-13145 Certs Fix - Backward compatibility for older clients. (#3014).

---

build/ansible/roles/pmm2-images/tasks/main.yml

PMM-7 Update gpg key to fix percona-release package installation.
Link to the Feature Build: SUBMODULES-3657

PMM-7 Update gpg key to fix percona-release package installation.

---

update/.devcontainer/install-dev-tools.sh

PMM-13197
**Issue**
Currently, the update workflow fails on some PMM image versions as yum can't reach RHEL repository mirrors.
**Solution**
In this PR we are working around the issue by changing the base URL to point to the archive.
Link to the Feature Build: N/A, since we are fixing the github workflow

PMM-13197 Fix update.yml workflow

---

managed/cmd/pmm-managed/main.go
managed/services/supervisord/devcontainer_test.go
managed/services/supervisord/logs.go
managed/services/supervisord/logs_test.go

PMM-13054
Link to the Feature Build: SUBMODULES-3651

PMM-13054 Increase the log line count

---

agent/runner/actions/mongodb_explain_action.go
agent/runner/actions/mongodb_explain_action_test.go
docs/release-notes/2.43.0.md
go.mod
go.sum

PR to merge it into V3.
V2 PR: https://github.com/percona/pmm/pull/3152 (merged)
Ticket: https://perconadev.atlassian.net/browse/PMM-12451

PMM-12451 MongoDB Explain - V3

---

build/Makefile

PMM-7 Pull ova box from s3 instead of vagrant cloud.

---

build/Makefile

* PMM-13385 Pull ova box from s3 instead of vagrant cloud.
* Update build/Makefile

PMM-13385 Pull ova box from s3 instead of vagrant cloud. (#3210)

---

build/docker/server/Dockerfile.el9

PMM-12641
Link to the Feature Build: SUBMODULES-3720

PMM-12641 Cleanup server build scripts

---

get-pmm.sh

PMM-12775 Install watchtower with PMM.

---

docker-compose.yml
update/ansible/playbook/tasks/roles/grafana/files/grafana.ini
update/ansible/playbook/tasks/roles/nginx/files/conf.d/pmm.conf

PMM-12593
Link to the Feature Build: SUBMODULES-3746

PMM-12593 Fix grafana renderer for PMM 2.

---

build/Makefile

PMM-13485
Link to the Feature Build: SUBMODULES-3758

PMM-13485 Fix ovf pipeline for v2

---

build/docker/server/Dockerfile.el9
managed/utils/envvars/parser.go
managed/utils/envvars/parser_test.go

PMM-13413
Link to the Feature Build: SUBMODULES-3744

PMM-13413 Do not run pillars telemetry

---

build/ansible/pmm-docker/post-build.yml
build/ansible/roles/pmm-images/tasks/main.yml
build/docker/server/Dockerfile.el9

PMM-7
Link to the Feature Build: SUBMODULES-3770
This PR is meant to solve the problem we are currently seeing at build time, during the execution of the ansible `dashboards` role: 
```
"stdout": "grafana: ERROR (not running)"
"stdout": "ERROR: process/group still running: grafana"
```
The problem is most probably due to the fact that we do not start `supervisord` as `pmm`, so it ends up being unable to stop a process owned by root. This leads to an eventual pipeline failure resulting in an interrupted build. 
The issues is not reproducible in 100% of builds, but may still be affecting more than 50% of v3 builds.

PMM-7 Run supervisor as pmm during build

---

build/ansible/roles/dashboards/tasks/main.yml
build/ansible/roles/pmm-images/tasks/main.yml

PMM-7
Link to the Feature Build: SUBMODULES-3773

PMM-7 Fix grafana stop/start

---

build/ansible/roles/dashboards/tasks/main.yml

PMM-7
Link to the Feature Build: SUBMODULES-3778
We are still seeing issues when we try to start grafana during the execution of the `dashboards` role. Reverting to `stop/remove/add` (as it was before) will hopefully fix it.

PMM-7 Better grafana start/stop handler

---

managed/services/victoriametrics/scrape_configs.go
managed/services/victoriametrics/scrape_configs_test.go

PMM-13571: Include fcv and pbm collectors in default scrape config

---

managed/services/agents/mongodb.go
managed/services/agents/mongodb_test.go
managed/services/victoriametrics/scrape_configs.go
managed/services/victoriametrics/scrape_configs_test.go

PMM-13571: increase min version to enable pbm collector

---

build/ansible/pmm2/post-build-actions.yml
build/ansible/roles/ami-ovf/tasks/main.yml
build/ansible/roles/cloud-node/tasks/main.yml
build/ansible/roles/supervisord-init/tasks/main.yml
build/scripts/build-client-rpm
build/scripts/build-client-srpm
build/scripts/build-server-rpm
update/ansible/playbook/tasks/roles/clickhouse/tasks/main.yml
update/ansible/playbook/tasks/roles/dashboards_upgrade/tasks/main.yml
update/ansible/playbook/tasks/roles/initialization/tasks/main.yml
update/ansible/playbook/tasks/roles/nginx/tasks/main.yml
update/ansible/playbook/tasks/roles/postgres/tasks/main.yml
update/ansible/playbook/tasks/update.yml

PMM-7
Link to the Feature Build: SUBMODULES-3796

PMM-7 Remove RHEL 7 build-related leftovers

---

documentation/docs/alert/contact_points.md
documentation/docs/alert/index.md
documentation/docs/configure-pmm/alertmanager.md
documentation/docs/reference/dashboards/dashboard-mongodb-replset-summary.md
documentation/docs/release-notes/3.0.0_Beta.md
documentation/docs/release-notes/3.0.0_GA.md
documentation/mkdocs-base.yml

PMM-12287 Document removal of Integrated Alerting

---

managed/services/grafana/client.go

PMM-13680
Due to automatic redirect to subpath if missing introduced in Grafana 9.5 the custom api endpoint was failing due to a redirect to a non-existing api (localhost:443 inside the container).
After introducing the subpath as part of the url it doesn't get redirected a works correctly.
Link to the Feature Build: SUBMODULES-3824

PMM 13680 Platform user api call

---

documentation/docs/how-to/secure.md

- Fix PMM Server port mapping
- Use `-v` to mount a volume vs `--volumes-from`, which is outdated

Fix PMM Server port mapping

---

.github/CONTRIBUTING.md
build/docker/server/README.md
documentation/docs/advisors/develop_advisor_checks.md
documentation/docs/alert/contact_points.md
documentation/docs/configure-pmm/configure.md
documentation/docs/install-pmm/HA.md
documentation/docs/install-pmm/install-pmm-server/baremetal/docker/index.md

It seems like this link leads nowhere other than the page itself, which duplicates the [Public address] section.
Apart from that, the way it's rendered on the page feels broken:
This PR also fixes the wrong port mappings in a few places.

Docs: update public-address page

---

documentation/docs/css/extra.css

Suggesting to contain the styling of the numbered lists inside the print media query, so that it can affect the PDF only but not the website (as it's happening now)
PMM-0

Isolate styling of numbered lists to PDF

---

README.md

Add login page initially pointing to blank page

---

build/Makefile
build/packer/ansible/roles/ami-ovf/tasks/main.yml

HD-26283 Fix removal of default vagrant user for OVA

---

.github/workflows/dependabot.yml

PMM-7
We are bumping up the dependabot's runner due to its forthcoming deprecation:
"The Ubuntu 20.04 runner image will be fully unsupported by April 1, 2025"
After the deprecation deadline, the actions will be blocked.

PMM-7 Bump up the runner to latest

---

build/docker/client/Dockerfile

PMM-13626
Link to the Feature Build: SUBMODULES-3863

PMM 13626 Install perl into pmm client

---

documentation/docs/release-notes/3.0.0.md

[DOCS] Rel Notes about ports change

---

documentation/docs/discover-pmm/supported-technologies.md

Removes empty page.
Even if not linked in the ToC it does appear in the search, and if clicked (from the search) it is shown online:
One approach is to refer to officially supported versions from this page (search "PMM 3 supported databases"):
- https://www.percona.com/services/policies/percona-software-support-lifecycle
We can consider to link this page when needed, to avoid the risk of having duplicate content.
Opening this PR to remove this empty page and for possible internal discussions, as appropriate.
In the hope this helps,

[DOCS] Removes empty "Supported Technologies" page

---

.devcontainer/setup.py

PMM-13748
Currently, #3738 is failing because it can't find the Kerberos header files while building `pmm-agent`. This adds the krb5-devel libraries in the devcontainer, so that the build can pass before we merge.
- https://github.com/percona/mongodb_exporter/pull/1042
- https://github.com/percona/pmm/pull/3738
- https://github.com/Percona-Lab/pmm-submodules/pull/3866/

PMM-13748 krb5 in devcontainer

---

documentation/README.md

Ensure Docker commands explicitly reference the correct MkDocs configuration files located in the `documentation` directory. Clarify setup steps by adding instructions for cloning the repository and navigating to the appropriate directory before building.
PMM-13777

PMM-13777 Update MkDocs commands to specify correct config paths

---

version/features.go

During the testing phase we had to force the version to pass the tests. Now that 3.2.0 is in the code, we need to revert it.
PMM-7

PMM-7 Revert mysqld_exporter version

---

managed/cmd/pmm-managed/main.go
managed/services/dump/dump.go

Enhanced the dump service to accept ClickHouse and VictoriaMetrics URLs. Updated the constructor and related logic to utilize these URLs for exports. Modified initialization in main.go to provide the required URL values.
PMM-13967
Link to the Feature Build: SUBMODULES-3916

PMM-13967 Add support for ClickHouse and VM URLs in dump service

---

.github/workflows/main.yml
agent/Makefile

PMM-13748
Link to the Feature Build: SUBMODULES-3919
- https://github.com/percona/mongodb_exporter/pull/1083
-

PMM-13748 drop gssapi support

---

documentation/docs/alert/templates_list.md

Page https://docs.percona.com/percona-monitoring-and-management/3/alert/templates_list.html
has strange "## Template catalog" section, see screenshot below:
This PR removes it.
If it was used for different reason, @catalinaadam  please let me know and we can try a different fix.
Thanks!

[DOCS] Alert templates - remove strange section

---

api-tests/server/auth_test.go
managed/services/grafana/auth_server.go

PMM-14021
Link to the Feature Build: SUBMODULES-3942

PMM-14021 change access level swagger

---

documentation/docs/setting-up/client/index.md

The volume path was incorrect for the pmm-client-data container, as it was using /srv/ when it should be using /usr/local/percona/pmm2/.
Also, what was mentioned about -d was incorrect, and using --rm as it was meant that the container will be removed when the process is stopped. It's better to use -d and leave it running in the background, and docker logs will still work in this case, so we don't lose any functionality.
PMM-0
- Links to related pull requests …

Changes in docker commands used.

---

ui/src/pages/updates/update-info/UpdateInfo.messages.ts

PMM-7
This fixes some typo errors on the updates page. Below is what those typos look like to the end user.

PMM-7 fix UI typo

---

api-tests/alerting/alerting_test.go
api-tests/inventory/agents_mysqld_exporter_test.go
api-tests/inventory/agents_test.go
api-tests/inventory/nodes_test.go
api-tests/inventory/services_test.go
api-tests/management/mysql_test.go

This PR addresses the following API test failures:
1. We added 8 more alert templates to the free tier via Portal, and now ListTemplates returns +8 templates.
2. It seems like [adding ExtraDsnParams](https://github.com/percona/pmm/pull/4221) broke some Inventory API tests. Example:
```bash
00:06:08.422          	            	Diff:
00:06:08.422          	            	--- Expected
00:06:08.422          	            	+++ Actual
00:06:08.422          	            	@@ -18,3 +18,4 @@
00:06:08.422          	            	   Version: (string) "",
00:06:08.422          	            	-  ExtraDsnParams: (map[string]string) <nil>
00:06:08.422          	            	+  ExtraDsnParams: (map[string]string) {
00:06:08.422          	            	+  }
```
Link to the Feature Build: SUBMODULES-4017
Test …

PMM-7 Fix Alerting and Inventory API tests

---

documentation/docs/install-pmm/install-pmm-client/connect-database/mysql/mysql.md

Updated MySQL documentation for user permissions and version support.
PMM-0

Revise MySQL user permissions and version references
