- proto/qan/qan.go
@daniel-nichter , please review this PR.
[related PR](https://github.com/percona/qan-api/pull/1)
> [PPL-75] Added schema of queries summary.

- proto/qan/qan.go
- added TotalQueries for Server Summary
> [PPL-77] Show number of queries in Profile

- doc/source/deploy/server/virtual-appliance.rst
Hi @azhebel , can you please review and merge, thanks!
> DOC-514 enhancing VMware content for Virtual Appliance

- doc/source/release-notes/1.3.0.rst
- doc/source/using.rst
> Update documentation based on review:

- doc/source/deploy/index.rst
- doc/source/release-notes/1.4.0.rst
> 1.4.0: Fix errors in documentation

- doc/source/deploy/server/ami.rst
- doc/source/pmm-admin.rst
- doc/source/release-notes/1.4.0.rst
- doc/source/release-notes/1.4.1.rst
> Release 1.4.1

- doc/source/pmm-admin.rst
- doc/source/release-notes/1.4.1.rst
> Documentation review:

- doc/source/.res/code/sh.org
- doc/source/.res/replace/option.txt
- doc/source/.res/replace/program.txt
- doc/source/.res/replace/url.txt
- doc/source/deploy/server/upgrade.rst
> Fix detected mistakes

- doc/source/.res/replace/fragment.txt
- doc/source/release-notes/1.6.1.rst
- doc/source/release-notes/1.8.0.rst
> Release notes 1.8.0: Minor changes:

- doc/source/.res/replace/name.txt
- doc/source/amazon-rds.rst
- doc/source/deploy/server/ami.rst
- doc/source/faq.rst
> PMM-1850: Corrections based on review:

- api/qanpb/json/client/metrics/get_metrics_responses.go
- api/qanpb/json/client/metrics/metrics_client.go
- api/qanpb/json/qanpb.json
- api/qanpb/metrics.pb.go
- api/qanpb/metrics.pb.gw.go
- api/qanpb/metrics.proto
- api/qanpb/metrics.validator.pb.go
- api/swagger/swagger.json
https://jira.percona.com/browse/PMM-3578
> PMM-3578 Update metrics.proto.

- api/inventorypb/agents.go
I don't understand WHY we have this exactly in this repo and FOR WHAT but nevermind.
> PMM-3879 Add MongoDBProfiler common code.

- api/agentpb/metadata.go
Also improve error message a bit.
> PMM-4076 Make metrics port optional for now.

- Gopkg.lock
- Gopkg.toml
> PMM-6214 Update logrus to fix an issue with 1.14

- .travis.yml
- README.md
https://jira.percona.com/browse/PMM-6213
> PMM-6213 Update Go

- README.md
Reverts percona/pmm#574
We should keep it in the list until we _really_ remove it everywhere.
> PMM-6766 Revert "Remove qan-app from list"

- markdown/dbaas.md
[PMM-8222](https://jira.percona.com/browse/PMM-8222)
Co-authored-by: Nurlan Moldomurov <nurlan.moldomurov@percona.com>
Co-authored-by: Denys Kondratenko <denys.kondratenko@percona.com>
> adding example sections for DBaaS API

- markdown/bulk-add-users.md
Added documentation to cover creating users and API tokens for PMM Server using the API.
> Added docs for bulk creating users and tokens

- markdown/change-admin-password.md
Added documentation to cover changing the administrator password
for PMM Server using the API.
> Change the administrator password via the API

- CONTRIBUTING.md
> PMM-10008 Fix links to pmm-admin and pmm-agent

- .github/workflows/ci.yml
> PMM-7 stabilize merge-gatekeeper

- api/inventorypb/agents.go
- api/inventorypb/nodes.go
- api/inventorypb/services.go
> Restore deleted interfaces

- .github/workflows/doc.yml
> PMM-0000 update readme.io ids

- .github/workflows/common.yml
> PMM-10212 Fixed sha for push events in github ci.

- managed/main.go
PMM-9910
Build: SUBMODULES-2593
> PMM-9910 Fix max GRPC message size

- admin/commands/management/add_mysql.go
PMM-10208
Build: SUBMODULES-2585
> PMM-10208 username flag fix

- managed/services/telemetry/config.default.yml
moved from https://github.com/percona/pmm-managed/pull/1131
> PMM-10068: fix stt flag

- go.mod
- go.sum
> Fix DBAAS dependency version

- CONTRIBUTING.md
> PMM-7 Update CONTRIBUTING.md

- CONTRIBUTING.md
> PMM-7 improve contribution guide

- agent/agentlocal/agent_local.go
- agent/agents/supervisor/supervisor.go
- agent/storelogs/storelogs.go
> PMM-5680 store agents logs review

- CONTRIBUTING.md
> PMM-7 fix link to pmm-managed

- managed/services/telemetry/config.default.yml
... according to suggestions in https://github.com/percona/pmm-doc/pull/818/
PMM-0
> PMM-10119 correct naming  ..

- agent/agents/process/process_test.go
PMM-10122
Build: SUBMODULES-2639
> PMM-10122 fix linters hint, pass test

- .devcontainer/setup.py
> PMM-5885 upgrade postgres version

- .github/CODEOWNERS
> PMM-7 Update CODEOWNERS

- agent/connectionchecker/connection_checker_test.go
> PMM-7 Fix unstable test

- .github/workflows/doc.yml
PMM-7
This should be a temporary fix, will revisit once we have a fix from readme.io
> PMM-7 fix readme pipeline

- code-of-conduct.md
> PMM-7 Fix Code of Conduct file header

- managed/services/supervisord/logs_test.go
> PMM-5680 skip with dynamic IDs now

- .github/workflows/common.yml
> PMM-7 Fix gatekeeper

- agent/connectionchecker/connection_checker.go
PMM-9118
Build: SUBMODULES-2652
> PMM-9118: improve error on x509 hostname mismatch

- .github/workflows/release-doc.yml
> PMM-7 Replace mkdocs commands to proper markdown

- agent/cmd/pmm-agent-entrypoint/main.go
> PMM-7 fix sidecar failing

- docs/process/common_tech_lib_approaches.md
> PMM-7 check for a string emptiness

- agent/agents/postgres/pgstatmonitor/pgstatmonitor.go
- agent/agents/postgres/pgstatmonitor/pgstatmonitor_models.go
- agent/agents/postgres/pgstatmonitor/pgstatmonitor_test.go
- agent/agents/postgres/pgstatmonitor/stat_monitor_cache.go
> PMM-10644 PGSM PG 11 and 12 bug.

- build/packages/rpm/client/pmm2-client.spec
PMM-10588
Build: SUBMODULES-2743
> PMM-10588 require perl for rhel9 or likes

- agent/agents/cache/cache.go
- agent/agents/cache/metrics.go
- agent/agents/mysql/perfschema/perfschema.go
PMM-10044
Build: SUBMODULES-2754
> PMM-10044 Fix enormous numbers in QAN.

- Dockerfile
- build/docker/rpmbuild/Dockerfile
- build/scripts/build-rpmbuild-docker
- managed/Makefile
PMM-10710
Build: SUBMODULES-2768
> PMM-10710 fix build

- managed/services/backup/backup_service.go
PMM-10720
Build: SUBMODULES-2773
> PMM-10720 Prevent resore of physical backups for MongoDB

- managed/services/agents/postgresql.go
- managed/services/agents/postgresql_test.go
- managed/services/agents/state.go
PMM-10714
Add postgres_exporter metrics endpoint auth via web.config
Build: SUBMODULES-2775
> PMM-10714 postgres-exporter auth

- .github/workflows/admin.yml
- .github/workflows/agent.yml
- .github/workflows/api.yml
- .github/workflows/clean.yml
- .github/workflows/common.yml
- .github/workflows/managed.yml
- api-tests/README.md
- devcontainer.Dockerfile
- managed/services/agents/postgresql.go
This PR fixes formatting after https://github.com/percona/pmm/pull/1210
> Fix formatting and update Go version up to 1.19

- build/docker/client/Dockerfile
> PMM-7: fix broken build

- build/ansible/roles/supervisord-init/files/supervisord.service
PMM-10735
Build: SUBMODULES-2791
- https://github.com/percona/pmm-update/pull/244
> PMM-10735 change service type

- .github/workflows/common.yml
> PMM-7 Don't crash build for optional linters

- .github/workflows/release-doc.yml
> PMM-7: do not run sed with no inputs

- agent/runner/jobs/mongodb_backup_job.go
- agent/runner/jobs/mongodb_restore_job.go
- agent/runner/jobs/pbm_helpers.go
- managed/services/backup/backup_service.go
> PMM-10470 physical backup restore

- managed/Makefile
Fixes bug introduced in https://github.com/percona/pmm/pull/1314
> PMM-7: fix makefile

- agent/runner/jobs/pbm_helpers.go
- agent/runner/jobs/pbm_helpers_test.go
> Backup fixes

- SECURITY.md
To view a rendered version head over [here](https://github.com/percona/pmm/blob/3fa2e9855b6c9f95a174bac1234b960e039f1f98/SECURITY.md)
> PMM-7 Create a security policy

- agent/agents/supervisor/supervisor.go
- agent/client/client.go
- agent/client/deps.go
- agent/client/mock_supervisor_test.go
- agent/runner/jobs/deps.go
- agent/runner/jobs/mongodb_restore_job.go
PMM-10944
Build: SUBMODULES-2851
> PMM-10944 Restart exporters after restore

- build/scripts/build-server-rpm-all
> PMM-7: fix pipeline error

- agent/runner/jobs/mongodb_backup_job.go
- agent/runner/jobs/mongodb_backup_job_test.go
- managed/cmd/pmm-managed/main.go
- managed/services/agents/jobs.go
- managed/services/management/backup/artifacts_service.go
- managed/services/management/backup/artifacts_service_test.go
- managed/services/management/backup/backups_service.go
- managed/services/management/backup/backups_service_test.go
- managed/services/management/backup/locations_service.go
- managed/services/management/backup/locations_service_test.go
- managed/services/management/backup/restore_history_service.go
> Rename backupv1beta1 to backupv1

- managed/services/agents/jobs.go
> Check pmm agent version for pitr restore

- managed/services/backup/backup_service.go
- managed/services/backup/compatibility_helpers.go
- managed/services/backup/errors.go
- managed/services/management/backup/backups_service.go
> Show correct error when artifact not ready for restore.

- managed/services/versioncache/versioncache_test.go
> PMM-7: fix failing test for commits

- build/packages/rpm/server/SPECS/dbaas-controller.spec
- build/packages/rpm/server/SPECS/percona-qan-api2.spec
- build/scripts/build-server-rpm-all
- build/scripts/create-tags.py
PMM-10117
Build: SUBMODULES-2876
- https://github.com/percona/pmm/pull/1040
> PMM-10117 migrate qan to monorepo

- .github/workflows/common.yml
> PMM-7 Enable reviewdog

- .github/workflows/release-doc.yml
> PMM-7: fix docs pipeline with empty grep

- agent/agents/mysql/perfschema/perfschema.go
- agent/agents/mysql/perfschema/perfschema_test.go
- agent/agents/mysql/slowlog/slowlog_test.go
- agent/runner/actions/common.go
- agent/runner/actions/mysql_explain_action_test.go
- agent/runner/actions/mysql_show_create_table_action_test.go
- agent/runner/actions/mysql_show_index_action_test.go
- agent/utils/tests/mysql.go
- agent/utils/version/mysql.go
- agent/utils/version/mysql_test.go
PMM-11077
Build: [FB](https://github.com/Percona-Lab/pmm-submodules/pull/2894)
> PMM-11077-pmm-ci-mariadb-tests-are-failing

- agent/client/client.go
- managed/services/checks/checks.go
- qan-api2/db.go
- qan-api2/db_test.go
- qan-api2/main.go
- qan-api2/models/metrics.go
- qan-api2/models/reporter.go
- qan-api2/services/analytics/filters.go
- qan-api2/services/analytics/object_details.go
- qan-api2/services/analytics/profile.go
- qan-api2/services/receiver/receiver.go
> PMM-7 Fix go-consistent warnings

- .devcontainer/setup.py
> PMM-7: fix slow tests on Ubuntu

- managed/Makefile
- managed/services/telemetry/config.default.yml
Remove test datapoint for testing JSON format
> PMM-7: Remove test datapoint for testing JSON format

- .github/CODEOWNERS
> PMM-7 Changed codeowners for PMM/DBaaS

- agent/runner/jobs/pbm_helpers.go
> PMM-11178 retry errors during PBM restore check

- .github/workflows/doc.yml
> PMM-7 Fix readme action version

- managed/services/telemetry/mock_data_source_test.go
PMM-7 - fix for aftermerge [pull/1285](https://github.com/percona/pmm/pull/1285)
> PMM-7 regenerated managed/services/telemetry/mock_data_source_test

- go.mod
- go.sum
> PMM-7 Fix dbaas dependency

- go.mod
- go.sum
- managed/cmd/pmm-managed/main.go
- managed/services/agents/channel/channel_test.go
- managed/services/telemetry/config.default.yml
- managed/utils/interceptors/grpc_extension.go
- managed/utils/interceptors/interceptors.go
- qan-api2/main.go
- qan-api2/utils/interceptors/interceptors.go
- utils/pdeathsig/pdeathsig_linux.go
[PMM-10541](https://jira.percona.com/browse/PMM-10541) [PMM-10948](https://jira.percona.com/browse/PMM-PMM-10948)
Build: SUBMODULES-2898
> PMM-10948 extend server gRPC metrics with caller_origin

- managed/services/supervisord/logs_test.go
> PMM-7: fix missing log file in tests

- managed/services/management/dbaas/kubernetes_server.go
> PMM-11370 Install VM operator first

- .github/dependabot.yml
> PMM-7 Fix dependabot config

- .github/dependabot.yml
> PMM-7 Add dependency reviewers

- tools/go.mod
- tools/go.sum
- tools/tools.go
- update/.devcontainer/install-dev-tools.sh
> PMM-7 Remove gopls

- .github/workflows/clean.yml
- .github/workflows/doc.yml
- .github/workflows/release-doc.yml
- .github/workflows/update.yml
- .github/workflowsbom-assest.yml
> PMM-7 Use same ubuntu version in all workflows

- .github/workflows/common.yml
- Makefile.include
> PMM-7 Update golangci-lint

- build/packages/rpm/server/SPECS/alertmanager.spec
PMM-11497
Build: SUBMODULES-3047
> PMM-11497 Update alert manager.

- update/ansible/playbook/tasks/roles/clickhouse/tasks/main.yml
PMM-7 Update clickhouse repository baseurl.
Build: SUBMODULES-3052
> PMM-7 Update clickhouse repository baseurl.

- .github/ISSUE_TEMPLATE/bug.yml
- .golangci.yml
- api-tests/server/auth_test.go
- api-tests/server/readyz_test.go
- api-tests/server/settings_test.go
- api-tests/server/version_test.go
- managed/services/grafana/auth_server_test.go
- managed/services/grafana/client_test.go
PMM-7
This PR fixes the `noctx` rule, which was previously disabled
> PMM-7 fix noctx linter warnings

- managed/services/management/dbaas/kubernetes_server_test.go
> PMM-7 Fix datarace

- managed/services/backup/backup_service.go
PMM-11687
Build: SUBMODULES-3076
> PMM-11687 Add retries for problematic tx

- .github/CODEOWNERS
> PMM-7 Added diogo to codeowners

- .github/pull_request_template.md
> PMM-7 add a reminder/checkbox to update API docs

- build/ansible/pmm2/post-build-actions.yml
- build/packer/pmm2.json
> Revert "PMM-11336 UUID generation ami"

- build/packages/rpm/server/SPECS/grafana.spec
- build/scripts/build-server-rpm
Cherry pick of 1640a3e7346553aa4ae62349010fa69d07ee72cd.
> PMM-11762 Update grafana to 9.2.13 (#1858)

- managed/cmd/pmm-managed-starlark/main.go
- managed/services/checks/checks.go
PMM-11808
Link to the Feature Build: SUBMODULES-3142
This PR reverts some changes related to data transferring introduced in https://github.com/percona/pmm/pull/1814
Also it adds base64 encoding for binary date before json serialization.
> PMM-11808 Fix query results deserialization bug

- .github/workflows/managed.yml
- Makefile.devcontainer
- managed/cmd/pmm-managed/main.go
- managed/services/supervisord/logs_test.go
PMM-7
Fixes bug introduced in https://github.com/percona/pmm/pull/1885
> PMM-7: Remove obsolete colons during creating addresses (it will be added by net.JoinHostPort function)

- build/packages/rpm/server/SPECS/victoriametrics.spec
- build/scripts/vars
PMM-11894
Feature Build: 
- https://github.com/Percona-Lab/pmm-submodules/pull/3171
> PMM-11894: update vm to 1.89.1

- build/docker/client/Dockerfile
PMM-11859
Link to the Feature Build: SUBMODULES-3181
> PMM-11859 Install jq to pmm-client docker image

- build/scripts/build-server-rpm
PMM-7
Link to the Feature Build: SUBMODULES-3193
> PMM-7 fix random server build failure due to EPEL's misconfiguration.

- managed/models/agent_model.go
- managed/models/agent_model_test.go
- managed/models/dsn_helpers_test.go
- managed/services/agents/mongodb_test.go
PMM-11849
Link to the Feature Build: SUBMODULES-3190
> PMM-11849 Set directConnection parameter in mongoDB DSN

- managed/services/management/rds.go
PMM-11853
Link to the Feature Build: SUBMODULES-3197
> PMM-11853 remove aurora from aws

- update/ansible/playbook/tasks/files/datasources.yml
PMM-10913
Link to the Feature Build: [SUBMODULES-3185](https://github.com/Percona-Lab/pmm-submodules/pull/3185)
> PMM-10913-typo-fix

- managed/models/database.go
PMM-10913
Link to the Feature Build: [SUBMODULES-3210](https://github.com/Percona-Lab/pmm-submodules/pull/3210)
> PMM-10913-internal-db-name-fix

- managed/services/config/pmm-managed.yaml
- managed/services/telemetry/config.default.yml
- managed/services/telemetry/telemetry.go
Reverts percona/pmm#1978
Reverting, since we reverted grafana DB migration
> Revert "PMM-11981: disable grafana telemetry"

- CONTRIBUTING.md
> PMM-7 Fix link to api tests

- agent/client/pbm.go
PMM-12050
Link to the Feature Build: SUBMODULES-3236
> PMM-12050 remove-direct-connection-for-pbm-pitr-switch.

- managed/services/management/grpc/actions_server.go
Action point from GO backend
https://www.notion.so/percona/Team-Weekly-30ec193fc3f140ea800de642667dbef0
> PMM-7 QAN Lint.

- update/ansible/playbook/tasks/roles/sqlite-to-postgres/tasks/main.yml
- update/ansible/playbook/tasks/update.yml
> fix UI upgrade

- update/ansible/playbook/tasks/update.yml
PMM-7
Link to the Feature Build: SUBMODULES-3273
> PMM-7 Fix build for el7 and el9 (PR-2081).

- build/ansible/roles/pmm2-images/tasks/main.yml
> PMM-7 fix grafana-db-migrator installation

- build/ansible/pmm2/post-build-actions.yml
- build/ansible/roles/supervisord-init/tasks/main.yml
- update/ansible/playbook/tasks/roles/clickhouse/tasks/main.yml
- update/ansible/playbook/tasks/roles/dashboards_upgrade/tasks/main.yml
- update/ansible/playbook/tasks/update.yml
PMM-7
Link to the Feature Build: SUBMODULES-3273
> PMM-7 Fix build for el7 and el9 (PR-2081)

- managed/services/supervisord/pmm_config.go
> PMM-7 Add missing postgresql parameter in supervisord configuration

- update/ansible/playbook/tasks/roles/postgres/tasks/main.yml
PMM-7
Link to the Feature Build: SUBMODULES-3279
This PR fixes the failing PMM update tests.
> PMM-7 fix PMM update ansible test

- .github/workflows/dockerhub-readme.yml
- build/docker/rpmbuild/Dockerfile.el9
- build/docker/server/README.md
PMM-12189
Note: it's a new action, and there is no way to test it before merging :)
> PMM-12189 automate updates of docker readme

- managed/services/supervisord/logs.go
- managed/services/supervisord/logs_test.go
PMM-7438
Link to the Feature Build: SUBMODULES-3200
> PMM-7438: fix reading long log lines

- scripts/authfix.sh
> PMM-12182 Create authfix.sh

- update/ansible/playbook/tasks/roles/postgres/tasks/main.yml
> PMM-12175 fix supervisorctl path for EL7.

- update/ansible/playbook/tasks/roles/initialization/tasks/main.yml
- update/ansible/playbook/tasks/update.yml
> PMM-12216 clean metadata

- build/docker/server/Dockerfile.el9
> PMM-12156 Update Dockerfile.el9 to fix server build.

- .github/dependabot.yml
> PMM-7 ignore patch updates.

- update/ansible/playbook/tasks/roles/postgres/tasks/main.yml
PMM-12175
Link to the Feature Build: SUBMODULES-3300
> PMM-12175 fix FB for EL7.

- update/ansible/playbook/tasks/roles/initialization/tasks/main.yml
> ENG-7 fix ansible

- update/ansible/playbook/tasks/update.yml
> PMM-7 fix pg version in ini file

- update/ansible/playbook/tasks/update.yml
> PMM-7 Update update.yml

- update/ansible/playbook/tasks/files/pmm.ini
- update/ansible/playbook/tasks/update.yml
PMM-12175
Link to the Feature Build: SUBMODULES-3308
> PMM-12175 revert pmm.ini

- update/pkg/yum/info.go
- update/pkg/yum/info_test.go
- update/pkg/yum/yum.go
PMM-12237
Link to the Feature Build: SUBMODULES-3311
> PMM-12237 fix the upgrade check failure

- update/pkg/yum/info.go
- update/pkg/yum/info_test.go
- update/pkg/yum/yum.go
PMM-12237
This is to bring the PR https://github.com/percona/pmm/pull/2289 to 2.38.0.
> PMM-12237 fix upgrade check failure

- build/packages/rpm/server/SPECS/dbaas-tools.spec
PMM-7
Link to the Feature Build: SUBMODULES-3301
> PMM-7 Upgrade aws-iam-authenticator.

- build/packages/rpm/server/SPECS/dbaas-tools.spec
> PMM-7 update aws iam authenticator 2.38

- build/ansible/roles/ami-ovf/tasks/main.yml
> PMM-12248 Fix supervisorctl path on EL-9. (#2301)

- build/ansible/roles/cloud-node/tasks/main.yml
> PMM-7 Fix user for OL9 AMI

- build/ansible/roles/cloud-node/tasks/main.yml
> PMM-7 Fix user for OL9 OVF (#2319)

- update/docker-compose.yml
- update/pkg/yum/info.go
- update/pkg/yum/info_test.go
- update/pkg/yum/yum.go
PMM-12266
Link to the Feature Build: SUBMODULES-3318
This PR:
- fixes parsing dates extracted from yum output on EL9
- adds tests for EL9
- conditionally runs yum tests depending on OS version
- it finally makes the test pipeline green again 🍏
> PMM-12266 fix parsing yum date format for EL9

- build/ansible/pmm2/post-build-actions.yml
> PMM-12136 force remove db 2.38

- build/packages/rpm/server/SPECS/grafana.spec
* PMM-12254 Update grafana spec to 9.2.20
* PMM-12254 Use commit hash for Grafana 9.2.20
> PMM-12254 Update grafana spec to 9.2.20 (#2315)

- .devcontainer/setup.py
- .github/workflows/managed.yml
- devcontainer.Dockerfile
- managed/services/supervisord/logs_test.go
PMM-12288
Link to the Feature Build: https://pmm.cd.percona.com/job/build-dev-container/1345/console
Note: the setup command in `setup.py` is failing, so we disabled it temporarily.
> PMM-12288 fix devcontainer build and tests

- .github/workflows/managed.yml
- managed/services/supervisord/supervisord.go
PMM-12293
Link to the Feature Build: SUBMODULES-3339
> PMM-12293 fix platform auth.

- managed/Makefile
- managed/cmd/pmm-managed-starlark/main_test.go
> PMM-7 Fix starlark test.

- .github/workflows/devcontainer.yml
This fixes the reference to docker.io secrets
PMM-12351
> PMM-12351 build devcontainer with gh actions

- update/ansible/playbook/tasks/roles/grafana/files/grafana.ini
> PMM-12393 cant login to PMM with SSO

- build/ansible/roles/pmm2-images/tasks/main.yml
- build/packages/rpm/server/SPECS/grafana-db-migrator.spec
- build/scripts/build-server-rpm-all
- update/ansible/playbook/tasks/roles/grafana/files/grafana.ini
- update/ansible/playbook/tasks/roles/grafana/tasks/main.yml
- update/ansible/playbook/tasks/roles/initialization/tasks/main.yml
- update/ansible/playbook/tasks/roles/sqlite-to-postgres/tasks/main.yml
- update/ansible/playbook/tasks/update.yml
> PMM-4466 Revert "PMM-12175 Revert #2017 Migrate Grafana to Postgres"

- build/scripts/create-tags
PMM-4817
Note: this ticket is closed, however we like to associate this PR with it for proper history.
> PMM-4817 use ssh vs https in create-tags script

- .github/workflows/dependabot.yml
PMM-12308
All dependabot PRs will be with enabled auto-merge option, but review and green CI will be still needed.
Here is how it looks like:
> PMM-12308 Add dependabot auto-merge workflow

- build/packages/rpm/server/SPECS/victoriametrics.spec
- build/scripts/vars
PMM-12346
Link to the Feature Build: SUBMODULES-3373
> PMM-12346 Update Victoria Metrics version.

- build/packages/rpm/server/SPECS/victoriametrics.spec
PMM-12346
Link to the Feature Build: SUBMODULES-3376
> PMM-12346 Update victoriametrics.spec

- update/ansible/playbook/tasks/update.yml
> PMM-7 Fix UI upgrade.

- .github/workflows/clean.yml
- build/docker/rpmbuild/Dockerfile
- build/docker/rpmbuild/Dockerfile.el9
- devcontainer.Dockerfile
- go.mod
- go.sum
- tools/go.mod
- tools/go.sum
- update/.devcontainer/install-dev-tools.sh
- update/docker-compose.yml
PMM-7
Link to the Feature Build: SUBMODULES-3395
> PMM-7 Update golang up to 1.21

- update/ansible/playbook/tasks/roles/clickhouse/tasks/main.yml
The test fails with "ERROR: no such process/group: clickhouse"
> PMM-7 Fix the upgrade test (dry-run)

- build/packages/deb/links
- build/packages/deb/postinst
Create links for files "pmm-admin" and "pmm-agent" which will be automatically deleted when the package is uninstalled.
> PMM-11280 Add links script for pmm client debian package

- build/scripts/build-server-rpm
PMM-12588
Test build - https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-submodules/detail/PR-3416/3/pipeline
> PMM-12588 Outdated grafana-db-migrator used

- build/packages/rpm/server/SPECS/grafana-db-migrator.spec
- build/scripts/build-server-rpm
- update/ansible/playbook/tasks/roles/initialization/tasks/main.yml
- update/ansible/playbook/tasks/roles/sqlite-to-postgres/tasks/main.yml
PMM-12592
PMM-12587
Link to the Feature Build: SUBMODULES-3414
> PMM-12592 PMM-12587 fix SQLite to PostgreSQL

- update/ansible/playbook/tasks/roles/sqlite-to-postgres/tasks/main.yml
> PMM-12587 Fix drop DB for EL7.

- update/ansible/playbook/tasks/roles/sqlite-to-postgres/tasks/main.yml
> PMM-7 ignore errors on not really necessary step.

- build/docker/rpmbuild/Dockerfile
- build/docker/rpmbuild/Dockerfile.el9
> PMM-7 Update golang up to 1.21.3

- build/docker/rpmbuild/Dockerfile
- build/docker/rpmbuild/Dockerfile.el9
> PMM-12626 Packages built using old go version

- agent/client/cache/cache.go
- agent/client/client.go
PMM-12632
Recreated with correct ticket number.
FB: https://github.com/Percona-Lab/pmm-submodules/pull/3427
> PMM-12632 Fix agent client response.

- update/ansible/playbook/tasks/roles/clickhouse/tasks/main.yml
> PMM-12630 UI upgrade from 2.37.1 and lower does not work

- managed/models/postgresql_version_test.go
- managed/services/backup/compatibility_service_test.go
> PMM-7 Fix tests

- .github/workflows/admin.yml
- .github/workflows/agent.yml
- .github/workflows/devcontainer.yml
- .github/workflows/doc.yml
- .github/workflows/main.yml
- .github/workflows/managed.yml
- .github/workflows/qan-api2.yml
- .github/workflows/update.yml
- .github/workflows/vmproxy.yml
- docker-compose.yml
> PMM-7 PMM v3 devcontainer builds

- .github/workflows/admin.yml
- .github/workflows/agent.yml
- .github/workflows/devcontainer.yml
- .github/workflows/doc.yml
- .github/workflows/main.yml
- .github/workflows/managed.yml
- .github/workflows/qan-api2.yml
- .github/workflows/update.yml
- .github/workflows/vmproxy.yml
- docker-compose.yml
> PMM-7 PMM v3 devcontainer (Restored PR)

- qan-api2/Makefile
- qan-api2/db.go
- qan-api2/db_test.go
- qan-api2/main.go
- qan-api2/models/reporter.go
- qan-api2/services/analytics/profile.go
- qan-api2/services/analytics/profile_test.go
PMM-12725
Link to the Feature Build: SUBMODULES-3464
> PMM-12725 fix QAN pagination.

- managed/services/backup/backup_service.go
- managed/services/backup/compatibility_service.go
- managed/services/management/backup/backups_service.go
PMM-12733
Link to the Feature Build: SUBMODULES-3467
> PMM-12733 Fix backup support for old PMM clients.

- update/ansible/playbook/tasks/roles/clickhouse/tasks/main.yml
- update/ansible/playbook/tasks/roles/dashboards_upgrade/tasks/main.yml
- update/ansible/playbook/tasks/roles/initialization/tasks/main.yml
PMM-12730
Link to the Feature Build: SUBMODULES-3466
> PMM-12730 Fix docker-way upgrade for < 2.22.0.

- api-tests/inventory/agents_azure_database_exporter_test.go
- api-tests/inventory/agents_external_exporter_test.go
- api-tests/inventory/agents_mongodb_exporter_test.go
- api-tests/inventory/agents_mysqld_exporter_test.go
- api-tests/inventory/agents_node_exporter_test.go
- api-tests/inventory/agents_postgres_exporter_test.go
- api-tests/inventory/agents_proxysql_exporter_test.go
- api-tests/inventory/agents_rds_exporter_test.go
- api-tests/inventory/agents_test.go
- api-tests/inventory/nodes_test.go
- api-tests/inventory/services_test.go
- api-tests/management/alerting/alerting_test.go
- api-tests/management/external_test.go
- api-tests/management/haproxy_test.go
- api-tests/management/helpers.go
- api-tests/management/mongodb_test.go
- api-tests/management/mysql_test.go
- api-tests/management/nodes_test.go
- api-tests/management/postgresql_test.go
- api-tests/management/proxysql_test.go
- api-tests/server/serialization_test.go
- managed/CONTRIBUTING.md
- managed/cmd/pmm-managed/main.go
- qan-api2/main.go
PMM-6722
Link to the Feature Build: SUBMODULES-3463
> PMM-6722 Preserve empty JSON fields in API responses

- update/ansible/playbook/tasks/roles/initialization/tasks/main.yml
PMM-12760
Link to the Feature Build: SUBMODULES-3479
> PMM-12760 fix offline upgrade failure.

- managed/services/ha/services.go
PMM-12761
Link to the Feature Build: SUBMODULES-3476
> PMM-12761 fix race condition for services.

- managed/services/server/server.go
> PMM-8306 fix ssh key bug

- build/scripts/build-client-deb
- build/scripts/build-client-sdeb
PMM-7 Fix pmm2-client source debian package.
> PMM-7 Fix pmm2-client source debian package.

- update/ansible/playbook/tasks/roles/initialization/tasks/main.yml
> PMM-7 Fix logout issue.

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/feature.yml
> PMM-7 Cleanup codeowners

- managed/models/agent_model.go
- managed/models/agent_model_test.go
- version/parsed_test.go
PMM-12807
Link to the Feature Build: SUBMODULES-3510
> PMM-12807 fix dsn generation

- managed/services/server/server.go
PMM-8306
Link to the Feature Build: SUBMODULES-3500
> PMM-8306 write SSH key to pmm user instead of root.

- managed/models/database.go
We try to re-use existing values for disabled checks and check intervals. But it is possible these values does not exist, leading to malformed JSON. This adds a null check, and only re-use these existing settings if they exist.
> PMM-12677 fix migrations

- .github/workflows/clean.yml
- Dockerfile
- build/docker/rpmbuild/Dockerfile
- build/docker/rpmbuild/Dockerfile.el9
- devcontainer.Dockerfile
- go.mod
- tools/go.mod
- tools/go.sum
- update/.devcontainer/install-dev-tools.sh
- update/docker-compose.yml
> PMM-7 Downgrade go to v1.21

- managed/data/iatemplates/postgresql_too_many_connections.yml
PMM-12992
Link to the Feature Build: SUBMODULES-3580
> PMM-12992 add service name to PostgreSQL connections in Use alert

- .github/workflows/agent.yml
- admin/Makefile
- agent/Makefile
- agent/docker-compose-pg-load.yml
- qan-api2/Makefile
- update/Makefile
> PMM-13043 Migrate to docker compose plugin v2

- build/ansible/roles/grafana/files/grafana.ini
PMM-13023
Link to the Feature Build: SUBMODULES-3608
> PMM-13023 Add leading slash to home dashboard path

- build/packages/rpm/server/SPECS/grafana.spec
PMM-13059
Related PRs:
- https://github.com/percona/grafana/pull/745
- https://github.com/percona/grafana-dashboards/pull/1591
> PMM-13059 Update grafana to 10.4.2

- go.mod
- managed/services/agents/channel/channel.go
- managed/services/agents/state.go
- managed/services/management/rds_test.go
- qan-api2/services/analytics/filters_test.go
- qan-api2/services/analytics/object_details_test.go
- qan-api2/services/analytics/profile_test.go
> PMM-7 Fix imports protobuf

- build/scripts/build-client-deb
PMM-13075
Link to the Feature Build: SUBMODULES-3619
> PMM-13075 Build pmm client for Ubuntu Noble (24..04)

- Dockerfile
- vmproxy/proxy/proxy.go
PMM-12776
Link to the Feature Build: SUBMODULES-3620
https://github.com/percona/grafana/pull/749
> PMM-12776 Update go version for API tests

- build/docker/rpmbuild/Dockerfile.el9
PMM-13137
Ref: https://pmm.cd.percona.com/job/rpm-build/92/console
> PMM-13137 Fix SHA1 deprecation in EL9

- managed/models/agent_helpers.go
- managed/models/agent_model.go
- managed/models/agent_model_test.go
- managed/models/dsn_helpers.go
- managed/services/agents/connection_checker.go
- managed/services/agents/mongodb.go
- managed/services/agents/mysql.go
- managed/services/agents/postgresql.go
- managed/services/agents/proxysql.go
- managed/services/agents/service_info_broker.go
- managed/services/agents/state.go
PMM-13145
Link to the Feature Build: https://github.com/Percona-Lab/pmm-submodules/pull/3636
It passed pmm2-upgrade-tests checks now.
> PMM-13145 Certs Fix - Backward compatibility for older clients.

- managed/services/server/updater.go
PMM-13028
Link to the Feature Build: SUBMODULES-3618
https://github.com/Percona-Lab/watchtower/pull/3
> PMM-13028 Non blocking StartUpgrade operation

- build/Makefile
- build/ansible/pmm2/post-build-actions.yml
- build/ansible/roles/pmm2-images/vars/main.yml
- build/packer/pmm2.el9.json
- build/packer/pmm2.json
- docs/managed/update-process.md
- qan-api2/docker-compose.yaml
- update/.devcontainer/install-dev-tools.sh
PMM-13197 Update scripts to stop using deprecated repos
Link to the Feature Build: SUBMODULES-3658
> PMM-13197 Update scripts to stop using deprecated repos

- build/ansible/roles/pmm2-images/tasks/main.yml
- build/docker/server/Dockerfile
- build/scripts/build-client-rpm
- build/scripts/build-client-srpm
- build/scripts/build-server-rpm
PMM-13222
Link to the Feature Build: SUBMODULES-3659
> PMM-13222 Fix server-autobuild-el7 pipeline after centos 7 eol.

- .github/workflows/managed.yml
- managed/services/supervisord/devcontainer_test.go
> PMM-7 Fix devcontainer test.

- api-tests/helpers.go
- api-tests/management/annotation_test.go
- api-tests/management/nodes_test.go
- managed/services/management/annotation.go
PMM-12857
Link to the Feature Build: SUBMODULES-3676
The API test run https://pmm.cd.percona.com/job/pmm3-api-tests/934/console
> PMM-12857 Fix API tests (part II)

- agent/runner/runner_test.go
> PMM-7 fix TestPerDBInstanceLimit.

- docs/release-notes/2.43.0.md
> PMM-12848 RelNotes entry  for New MongoDB collector: CurrentOp

- docs/release-notes/2.43.0.md
> PMM-12869 - Rel-Notes-for-improved-troubleshooting

- build/packer/ansible/agent-do.yml
- build/packer/do.pkr.hcl
> PMM-13244 Drop centos-7 ovf agent

- build/scripts/build-submodules
Same as https://github.com/percona/pmm/pull/3184, but for v3.
- https://github.com/Percona-Lab/jenkins-pipelines/pull/2830
> PMM-7 Move build-submodules script to monorepo (v3)

- api-tests/management/services/agent_test.go
PMM-7
Link to the Feature Build: SUBMODULES-3701
> PMM-7 Fix agent API test

- api-tests/Makefile
- api-tests/server/settings_test.go
- managed/services/server/server.go
PMM-7
Link to the Feature Build: SUBMODULES-3715
> PMM-7 fix SSH key test.

- update/ansible/playbook/tasks/update.yml
> PMM-13384 enable percona telemetry repo

- docs/release-notes/2.43.0.md
> PMM-13141 add release notes.

- admin/commands/management/remove.go
PMM-13502
Link to the Feature Build: SUBMODULES-3759
> PMM-13502 pmm admin remove fix

- api/swagger/swagger-dev.json
- api/swagger/swagger.json
- managed/services/management/rds.go
> PMM-12013 Fix scrapeconfig generation for rds exporter.

- .github/workflows/main.yml
- Makefile.include
> Update golangci-lint version up to 1.62.0

- docs/api/release-notes/3.0.0.Beta.md
PMM-7
This seems to fix the issue with multiple links on readme.
> PMM-7 Fix v3.0.0-beta RN link on readme

- build/ansible/roles/initialization/tasks/main.yml
- build/packer/ansible/roles/ami-ovf/tasks/main.yml
- build/packer/ansible/roles/podman-setup/tasks/main.yml
- build/packer/ansible/roles/podman-setup/templates/pmm-server.env
PMM-13567
Link to the Feature Build: SUBMODULES-3781
> PMM-13567 fix ami ovf build

- build/scripts/build-client-srpm
PMM-7
To rectify the failure: https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-client-autobuilds-amd/detail/pmm2-client-autobuilds-amd/224/pipeline/
> PMM-7 Fix build-client-srpm failure

- documentation/docs/setting-up/client/mongodb.md
PMM-7
Porting https://github.com/percona/pmm-doc/pull/1346 over here
> PMM-7 update MongoDB client setup

- documentation/docs/release-notes/3.0.0.md
> mentioned upgrade option in rel notes

- documentation/docs/release-notes/3.0.0.md
> RelNotes for PMM-13633

- documentation/docs/release-notes/3.0.0.md
> ReLNotes entry for new container size image

- managed/models/agent_helpers.go
PMM-13673
Link to the Feature Build: https://github.com/Percona-Lab/pmm-submodules/pull/3827
> PMM-13673 Remove unicode nils in cert files.

- documentation/docs/install-pmm/install-pmm-client/connect-database/mongodb.md
- documentation/docs/pmm-upgrade/upgrade_client.md
> Replicate pr 3460 from pmm2 docs

- managed/models/settings_helpers_test.go
> PMM-7 fix test.

- documentation/docs/release-notes/3.0.0.md
> RelNotes entry about Docker Image label changes

- documentation/docs/reference/dashboards/dashboard-mongodb-router-summary.md
- documentation/mkdocs-base.yml
> Document mongo db router summary dashboard

- build/ansible/roles/postgres/tasks/main.yml
PMM-13679
Link to the Feature Build: SUBMODULES-3828
> PMM-13679 Fix postgres directory ownership.

- documentation/docs/install-pmm/install-pmm-server/baremetal/docker/restore_container.md
- documentation/docs/pmm-upgrade/migrating_from_pmm_2.md
- documentation/docs/pmm-upgrade/upgrade_docker.md
- documentation/docs/pmm-upgrade/upgrade_podman.md
> Document backup restore following automatic upgrade

- get-pmm.sh
> PMM-13662 Fix backup from data container

- documentation/docs/how-to/HA.md
Remove old reference to specific quarter.
Can be improved more depending on review - but for now removed wrong quarter.
Thanks.
> Doc v2 - HA: remove reference to specific quarter

- docs/api/release-notes/3.0.0.md
> PMM-13077 Document PMM versions endpoint [render preview]

- documentation/docs/install-pmm/install-pmm-server/baremetal/podman/index.md
> PMM-7 install podman doc improvement

- .github/workflows/documentation.yml
- documentation/docs/index.md
- documentation/docs/install-pmm/install-pmm-server/aws/aws.md
> updated tag and references to pmm demo environement

- documentation/docs/install-pmm/install-pmm-server/baremetal/podman/index.md
- documentation/docs/pmm-upgrade/upgrade_podman.md
> PMM-13713 fix podman documentation to handle watchtower upgrade

- documentation/docs/install-pmm/install-pmm-client/prerequisites.md
- documentation/docs/install-pmm/install-pmm-server/prerequisites.md
- documentation/docs/install-pmm/plan-pmm-installation/hardware_and_system.md
- documentation/docs/install-pmm/plan-pmm-installation/network_and_firewall.md
> Pmm 12578 document recommended pmm server size

- .github/workflows/documentation.yml
- documentation/docs/index.md
- documentation/docs/quickstart/index.md
- documentation/overrides/main.html
> PMM-13503 changes following PMM 3 GA

- .github/workflows/documentation.yml
> PMM-7 Don't publish v2 docs as default version

- documentation/docs/get-help.md
- documentation/docs/index.md
- documentation/docs/release-notes/3.0.0.md
- documentation/mkdocs-base.yml
> Fixed content not rendered

- .github/workflows/documentation.yml
- docs/api/release-notes/3.0.0.md
> PMM-7 Publish v3 as the default docs version

- documentation/docs/install-pmm/install-pmm-client/connect-database/mysql.md
> improve password security references

- .github/workflows/release-doc.yml
> PMM-7 Fix release-doc pipeline

- documentation/docs/install-pmm/install-pmm-client/package_manager.md
> Changed repository enable command to use testing repository

- documentation/overrides/main.html
> fix top banner

- documentation/docs/api/authentication.md
- documentation/docs/api/index.md
> improved topic and corrected step number

- documentation/docs/setting-up/client/mysql.md
- documentation/overrides/main.html
> improved password security references for PMM2

- documentation/overrides/partials/header.html
> Fixed top link text and target

- documentation/docs/install-pmm/install-pmm-client/package_manager.md
- documentation/docs/install-pmm/install-pmm-server/baremetal/docker/index.md
- documentation/docs/install-pmm/install-pmm-server/baremetal/docker/run_with_host_dir.md
- documentation/docs/install-pmm/install-pmm-server/baremetal/docker/run_with_vol.md
- documentation/docs/pmm-upgrade/index.md
- documentation/docs/pmm-upgrade/ui_upgrade.md
- documentation/docs/pmm-upgrade/upgrade_client.md
> Fixed links and incorrect references in upgrade and Install with Docker

- documentation/overrides/partials/header.html
> Update banner link 

- documentation/docs/backup/mongodb-backup/backup_mongo.md
> [DOC] Replicate PR3527 for v3

- documentation/docs/css/design.css
> DOCS-135 Fix the colour of the search results in dark mode (2.0)

- documentation/docs/css/design.css
> DOCS-135 Fix the colour of the search results in dark mode (3.0)

- documentation/docs/setting-up/server/easy-install.md
> Fix the `easy install` script to point to v2 on 'main'

- README.md
> Added jpg pics which where previously pointing to 404 page

- build/Makefile
- build/ansible/roles/ami-ovf/tasks/main.yml
> HD-26283 Fix removal of default vagrant user for OVA

- vmproxy/proxy/proxy.go
- vmproxy/proxy/proxy_test.go
> vmproxy: always set Host header from VMURL

- get-pmm.sh
> PMM-13726 Error message for docker install failure.

- build/Makefile
- build/ansible/roles/postgres/tasks/main.yml
- build/packer/ansible/roles/ami-ovf/tasks/main.yml
> PMM-7 merge release branch to v3

- build/Makefile
- build/ansible/roles/postgres/tasks/main.yml
- build/packer/ansible/roles/ami-ovf/tasks/main.yml
> PMM-7 merge release change from pmm-3.0.0

- documentation/docs/install-pmm/install-pmm-server/deployment-options/docker/run_with_host_dir.md
> [DOCS] Standardize Docker network name 2

- documentation/docs/install-pmm/install-pmm-server/deployment-options/docker/easy-install.md
> [Docs]Update install script URL to percona.com/get/pmm

- documentation/Makefile
> PMM-7 [DOCS] Add the preview and search commands

- documentation/docs/release-notes/2.44.0.1.md
> [Docs] Updated 2.44.0-1 to mention not affected installations

- documentation/docs/get-help.md
> DOCS-159 Implement the Lead generation forms (3.0)

- documentation/docs/get-started/alert-templates.md
> [DOCS]Fix table

- documentation/docs/install-pmm/install-pmm-server/deployment-options/docker/easy-install.md
- documentation/docs/reference/faq.md
> [DOCS] Document Easy-Insall error on Rocky - PMM-13726

- build/scripts/vars
> PMM 7 Fix rpmbuild version to 3

- documentation/docs/release-notes/2.43.2-1.md
- documentation/docs/release-notes/2.43.2.md
- documentation/docs/release-notes/2.44.0.1.md
- documentation/docs/release-notes/2.44.0.md
- documentation/docs/release-notes/index.md
- documentation/mkdocs-base.yml
> [DOCS] Rel Notes for PMM 2.43.2-1

- build/Makefile
> PMM 13851 Fix ova build

- build/Makefile
> PMM-13851 Fix ova build for v2.

- documentation/docs/admin/security/ssl_encryption.md
> PMM-7 Update ssl_encryption.md

- agent/agents/mongodb/internal/profiler/fingerprinter/fingerprinter.go
- agent/agents/mongodb/internal/profiler/fingerprinter/fingerprinter_test.go
- agent/agents/mongodb/internal/profiler/parser/parser.go
Fix namespace parsing and improve logging in fingerprinter.
PMM-13894
Link to the Feature Build: SUBMODULES-3877
> PMM-13894 Fix pmm-agent crash for update queries

- get-pmm.sh
> PMM-7 Update get-pmm.sh

- documentation/docs/release-notes/3.1.0.md
- documentation/mkdocs-pdf.yml
- documentation/variables.yml
> [DOCS] Update date

- docs/api/welcome/monitoring.md
> [DOCS] Fix 404 API

- documentation/docs/release-notes/2.42.0-1.md
- documentation/docs/release-notes/index.md
- documentation/mkdocs-base.yml
> [DOCS] RelNotes for 2.42.0-1

- managed/cmd/pmm-managed/packages.dot
- managed/models/agent_helpers.go
- managed/models/agent_helpers_test.go
- managed/models/agent_model_test.go
- managed/models/dsn_helpers_test.go
- managed/services/agents/registry.go
- managed/services/agents/state.go
- managed/services/inventory/agents.go
- managed/services/inventory/inventory_metrics.go
- managed/services/management/agent.go
- managed/services/management/grpc/actions_server.go
- managed/services/management/node.go
- managed/services/management/service.go
- managed/utils/encryption/encryption.go
PMM-13937
Link to the Feature Build: SUBMODULES-3900
> PMM-13937 Add support to filter out Nomad agents when disabled

- documentation/docs/release-notes/2.44.1.md
> [Docs] Fix typo

- .github/workflows/release-doc.yml
PMM-7
Last failure: https://github.com/percona/pmm/actions/runs/14640797785/job/41145956414
> PMM-7 Fix release doc workflow

- documentation/Makefile
> PMM-7 Fix doc PDF file generation

- documentation/docs/copyright.md
- documentation/mkdocs-pdf.yml
> [Docs]Update PMM2 PDF copyright

- agent/agents/mysql/perfschema/perfschema_test.go
- go.mod
- go.sum
PMM-13807
Link to the Feature Build: SUBMODULES-3904
- https://github.com/percona/go-mysql/pull/64
> PMM-13807 fingerprint keywords

- README.md
Link to installation doc and login image were wrong.
> README.md - v3 - Fix broken link and image

- README.md
Link to installation doc was broken
> REAME.md - v2 - fix broken link

- .github/workflows/agent.yml
PMM-7
This PR removes unsupported version from PMM Agent v3 tests.
> PMM-7 Remove unsupported versions from agent tests

- documentation/docs/release-notes/2.44.1.md
> [DOCS] Known issue 2.44.1 (PMM-13956)

- managed/services/supervisord/supervisord.go
> PMM-13969 fix vmalert startup

- documentation/docs/reference/pmm_components_and_versions.md
- documentation/docs/release-notes/3.2.0.md
> PMM-13210 - Update changelog and components versions.

- docs/process/v2_to_v3_environment_variables.md
- documentation/docs/reference/third-party/clickhouse.md
> PMM-13171 Add ClickHouse security best practices

- build/packer/aws.pkr.hcl
> PMM-7 Increase jenkins agent space.

- build/docker/rpmbuild/Dockerfile.el8
- build/docker/rpmbuild/Dockerfile.el9
- build/docker/server/Dockerfile.el9
PMM-7
This PR aims at reducing the server image size by leveraging the cache mounts.
> PMM-7 Leverage cache mounts for the server

- build/ansible/roles/initialization/tasks/main.yml
- docker-compose.yml
- managed/cmd/pmm-managed/main.go
- managed/services/ha/services.go
- managed/services/server/server.go
- managed/testdata/haproxy/haproxy.cfg
- managed/testdata/pg/conf/pg_hba.conf
> Revert "PMM-13794: Add HAService integration to server initialization"

- documentation/docs/troubleshoot/pmm_dump.md
PMM-7
Moving https://github.com/percona/pmm/pull/3949 over here.
> PMM-7 PMM Dump doc fixes

- go.mod
- go.sum
> PMM-13978 Add back correct PT version.

- go.mod
- go.sum
* PMM-13978 Add back correct PT version.
* PMM-13978 Tidy.
PMM-0
> PMM-13978 Add back correct PT version. (#4035)

- build/packages/rpm/server/SPECS/grafana.spec
PMM-14005
Related PRs:
- https://github.com/percona/grafana/pull/820 (RC branch)
- https://github.com/percona/grafana/pull/819
FB: https://github.com/Percona-Lab/pmm-submodules/pull/3931
> PMM-14005 Grafana 11.6.1

- build/packages/rpm/server/SPECS/grafana.spec
Cherry pick of 1fce657ca1ff613164d0e938283f604e7336a88d
> PMM-14005 Grafana 11.6.1 (#4039)

- build/docker/rpmbuild/Dockerfile.el8
> PMM-14051 Fix pmm3 client autobuild.

- build/ansible/ansible.cfg
PMM-14084
Link to the Feature Build: SUBMODULES-3963
> PMM 14084 Fix server docker build

- .github/workflows/dependabot.yml
> PMM-7 Update dependabot.yml

- documentation/docs/pmm-upgrade/migrating_from_pmm_2.md
> [DOCS] Specify PMM 2 EOL (PMM-14008)

- documentation/docs/install-pmm/install-pmm-client/connect-database/mongodb.md
- documentation/docs/install-pmm/install-pmm-client/connect-database/mysql/mysql.md
- documentation/docs/install-pmm/install-pmm-client/connect-database/postgresql.md
- documentation/docs/pmm-upgrade/migrating_from_pmm_2.md
- documentation/docs/reference/dashboards/dashboard-mysql-table-details.md
- documentation/docs/reference/faq.md
- documentation/docs/release-notes/3.3.0.md
- documentation/docs/troubleshoot/qan_issues.md
> [DOCS] Warn about incorrect query plan metrics (PMM-13712)

- build/scripts/build-client-binary
- build/scripts/vars
> PMM-14113 revert nomad cache

- qan-api2/models/metrics.go
PMM-13978
Link to the Feature Build: https://github.com/Percona-Lab/pmm-submodules/pull/3973
> PMM-13978 Fix for tables, plan.

- build/Makefile
> PMM-14126 Revert packer's version back to 1.9.4 to fix build.

- api-tests/inventory/nodes_test.go
- managed/services/converters.go
PMM-14151
Link to the Feature Build: SUBMODULES-3978
> [!NOTE]
> The API tests succeeded - https://github.com/Percona-Lab/pmm-submodules/pull/3978#issuecomment-3032294563
> PMM-14151 Fix TlsSkipVerify value in GetAgent response

- build/scripts/build-client-docker
PMM-14143
Link to the Feature Build: SUBMODULES-3999
> PMM-14143 dynamic tarballs scripts

- documentation/docs/configure-pmm/advanced_settings.md
> PMM-7 Fix the alert block

- documentation/docs/quickstart/quickstart.md
Add missing permissions and info about Mongo8
Fixed the pmm port
PMM-0
> PMM-14225 Update quickstart.md

- documentation/docs/install-pmm/install-pmm-client/package_manager.md
- documentation/docs/install-pmm/install-pmm-server/index.md
- documentation/docs/pmm-upgrade/migrating_from_pmm_2.md
- documentation/docs/release-notes/3.3.1.md
> [DOC]Update 3.3.1

- documentation/docs/index.md
> [DOC] Remove EOL date

- build/ansible/roles/nginx/files/conf.d/pmm.conf
- build/docker/client/Dockerfile.el9
PMM-14166
Link to the Feature Build: SUBMODULES-4006
- https://github.com/percona/grafana/pull/837
> PMM-14166 Fix image renderer port

- documentation/docs/alert/templates_list.md
Do not merge until the corresponding https://github.com/percona/checked/pull/1136 is merged and deployed to prod
---
When the following PR will be merged and released , the documentation needs to be updated as well.
https://github.com/percona/checked/pull/1136
PMM-0
> Update templates_list.md -  add Stale PBM backups

- api-tests/alerting/alerting_test.go
- api-tests/inventory/agents_mysqld_exporter_test.go
- api-tests/management/services/agent_test.go
Need to revert some accidental changes made during the previous fix :)
PMM-7
Link to the Feature Build: SUBMODULES-4020
All tests pass: https://pmm.cd.percona.com/job/pmm3-submodules/1524/console
> PMM-7 Fix API tests

- documentation/docs/install-pmm/install-pmm-client/binary_package.md
- documentation/docs/install-pmm/install-pmm-client/docker.md
- documentation/docs/install-pmm/install-pmm-client/package_manager.md
> Merge  pr4379

- build/docker/server/Dockerfile.el9
PMM-7
Link to the Feature Build: SUBMODULES-4026
> PMM-7 Change Dockerfile to use 'pmm' user instead of UID 1000

- documentation/docs/install-pmm/install-pmm-client/package_manager.md
Updated the command to register using a token by combining the server URL, username, and password into a single URL format.
PMM-0
> PMM-7 Fix PMM client registration command

- .devcontainer/Dockerfile
- build/docker/server/Dockerfile.el9
> Revert "PMM-7 Change Dockerfile to use 'pmm' user instead of UID 1000"

- build/ansible/roles/nginx/files/ssl/generate-ssl-certificate
PMM-14299
Link to the Feature Build: SUBMODULES-4031
> PMM-14299 Fix exit status in generate-ssl-certificate script

- documentation/docs/index.md
- documentation/docs/release-notes/3.4.0.md
- fix for improper Jira ticket reference
PMM-0
> Update 3.4.0.md RN

- build/scripts/build-client-binary
PMM-14334
Link to the Feature Build: SUBMODULES-4044
> PMM-14334 Fix pmm-client-autobuild pipeline.

- documentation/docs/release-notes/2.41.2.md
External services link update
PMM-0
> PMM-14167 - Update 2.41.2.md
